
export const authTypes = {
    SET_USER: 'SET_USER',
    SET_LOADING: 'SET_LOADING',
    SIGN_OUT: 'SIGN_OUT',
    SET_ERROR: 'SET_ERROR',
    NEED_VERIFICATION: 'NEED_VERIFICATION',
    SET_SUCCESS: 'SET_SECCESS',
};